version = "3.9.10"
runner.dialect = scala3

maxColumn = 120

align.preset = none
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.source = keep

rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers, Imports]
rewrite.imports.sort = scalastyle
rewrite.redundantBraces.stringInterpolation = true

runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false
# allows `if x then y`
runner.dialectOverride.allowQuietSyntax = true

docstrings.style = Asterisk
docstrings.wrap = no

project.excludePaths = [
  "glob:**/.scala-build/**",
  "glob:**/target/**",
  "glob:**/node_modules/**",
  "glob:**/frontend/**"
]
