openapi: 3.1.0
info:
  title: Personal App API
  version: '1.0'
paths:
  /wishlist/albums:
    get:
      operationId: List Wishlist Albums
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WishlistAlbum'
    post:
      operationId: Add Album to Wishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAlbumToWishlist'
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
  /wishlist/albums/{id}/received:
    post:
      operationId: Confirm Album Received
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
  /wishlist/albums/{id}/order:
    post:
      operationId: Order Album
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
  /albums:
    get:
      operationId: List Albums
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartialAlbum'
    post:
      operationId: Create Album
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlbum'
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
  /albums/{albumId}:
    get:
      operationId: Get Album By ID
      parameters:
      - name: albumId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartialAlbum'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
  /albums/{albumId}/genres:
    post:
      operationId: Add Genre To Album
      parameters:
      - name: albumId
        in: path
        required: true
        schema:
          type: string
      - name: genre
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: query parameter genre'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      operationId: Remove Genre From Album
      parameters:
      - name: albumId
        in: path
        required: true
        schema:
          type: string
      - name: genre
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: query parameter genre'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /albums/{albumId}/review:
    post:
      operationId: Review Album
      parameters:
      - name: albumId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
  /guitars:
    get:
      operationId: List Guitars
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guitar'
  /guitars/{id}/events:
    get:
      operationId: Get Guitar Events
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GuitarEvent'
        '404':
          description: ''
  /guitars/{id}/commands:
    post:
      operationId: Handle Guitar Command
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuitarCommand'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guitar'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
  /guitars/{id}/string-recommendation:
    post:
      operationId: Recommend Strings
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StringRecommendationRequest'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringRecommendationResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
  /amplifiers:
    get:
      operationId: List Amplifiers
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Amplifier'
  /guitar-pedals:
    get:
      operationId: List Guitar Pedals
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GuitarPedal'
components:
  schemas:
    AddAlbumToWishlist:
      title: AddAlbumToWishlist
      type: object
      required:
      - name
      - artist
      - format
      - releaseDate
      - status
      properties:
        name:
          type: string
        artist:
          type: string
        format:
          $ref: '#/components/schemas/AlbumFormat'
        releaseDate:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/WishlistStatus'
    AlbumFormat:
      title: AlbumFormat
      type: string
      enum:
      - CD
      - Vinyl
    AmpType:
      title: AmpType
      type: string
      enum:
      - SolidState
      - Tube
    Amplifier:
      title: Amplifier
      type: object
      required:
      - id
      - model
      - serialNumber
      - brand
      - year
      - wattage
      - type
      properties:
        id:
          type: string
        model:
          type: string
        serialNumber:
          type: string
        brand:
          $ref: '#/components/schemas/AmplifierBrand'
        year:
          type: integer
          format: int32
        wattage:
          type: integer
          format: int32
        type:
          $ref: '#/components/schemas/AmpType'
    AmplifierBrand:
      title: AmplifierBrand
      type: string
      enum:
      - Revv
      - Victory
    BadRequest:
      title: BadRequest
      type: object
      required:
      - message
      properties:
        message:
          type: string
    ChangeStrings:
      title: ChangeStrings
      type: object
      required:
      - date
      - stringBrand
      - tuning
      properties:
        date:
          type: string
          format: date
        stringBrand:
          type: string
        stringGauge:
          type: array
          items:
            type: number
            format: double
        tuning:
          $ref: '#/components/schemas/GuitarTuning'
    CreateAlbum:
      title: CreateAlbum
      type: object
      required:
      - name
      - artist
      - format
      - releaseDate
      properties:
        name:
          type: string
        artist:
          type: string
        format:
          $ref: '#/components/schemas/AlbumFormat'
        releaseDate:
          type: string
          format: date
    Guitar:
      title: Guitar
      type: object
      required:
      - id
      - model
      - brand
      - year
      - serialNumber
      - specifications
      - setup
      properties:
        id:
          type: string
        model:
          type: string
        brand:
          $ref: '#/components/schemas/GuitarBrand'
        year:
          type: integer
          format: int32
        serialNumber:
          type: string
        specifications:
          $ref: '#/components/schemas/GuitarSpecifications'
        setup:
          $ref: '#/components/schemas/GuitarSetup'
        events:
          type: array
          items:
            $ref: '#/components/schemas/GuitarEvent'
    GuitarBrand:
      title: GuitarBrand
      type: string
      enum:
      - Aristides
      - Charvel
      - Dunable
      - Epiphone
      - Ibanez
      - Jackson
      - Ltd
      - PRS
      - Schecter
    GuitarCommand:
      title: GuitarCommand
      oneOf:
      - $ref: '#/components/schemas/ChangeStrings'
    GuitarEvent:
      title: GuitarEvent
      oneOf:
      - $ref: '#/components/schemas/StringsChanged'
    GuitarMaterial:
      title: GuitarMaterial
      type: string
      enum:
      - Alder
      - Arium
      - Ash
      - Basswood
      - Ebony
      - FlamedMaple
      - MacassarEbony
      - Mahogany
      - Mango
      - Maple
      - PauFerro
      - PoplarBurl
      - PurpleHeart
      - QuiltedMaple
      - RichLite
      - RoastedMaple
      - Rosewood
      - SwampAsh
      - Walnut
      - Wenge
    GuitarPedal:
      title: GuitarPedal
      type: object
      required:
      - id
      - model
      - serialNumber
      - brand
      - year
      - type
      properties:
        id:
          type: string
        model:
          type: string
        serialNumber:
          type: string
        brand:
          $ref: '#/components/schemas/GuitarPedalBrand'
        year:
          type: integer
          format: int32
        type:
          $ref: '#/components/schemas/PedalType'
    GuitarPedalBrand:
      title: GuitarPedalBrand
      type: string
      enum:
      - Boss
      - Digitech
      - EarthQuakerDevices
      - Fortin
      - GroundFx
      - Hologram
      - JHS
      - JPTRFX
      - KMAMachines
      - Klirrton
      - LichtlaermAudio
      - OldBloodNoiseEndeavors
      - Revv
      - ScienceAmplification
      - SeymourDuncan
      - StoneDeaf
      - TcElectronic
      - WalrusAudio
      - WayHuge
    GuitarSetup:
      title: GuitarSetup
      type: object
      required:
      - stringBrand
      - tuning
      - lastStringChange
      properties:
        stringGauge:
          type: array
          items:
            type: number
            format: double
        stringBrand:
          type: string
        tuning:
          $ref: '#/components/schemas/GuitarTuning'
        lastStringChange:
          type: string
          format: date
    GuitarSpecifications:
      title: GuitarSpecifications
      type: object
      required:
      - bodyFinish
      - bodyMaterial
      - pickupConfiguration
      - fretboardMaterial
      - numberOfFrets
      - scaleLengthInInches
      - numberOfStrings
      properties:
        bodyFinish:
          type: string
        top:
          $ref: '#/components/schemas/GuitarMaterial'
        bodyMaterial:
          $ref: '#/components/schemas/GuitarMaterial'
        pickupConfiguration:
          $ref: '#/components/schemas/PickupConfiguration'
        fretboardMaterial:
          $ref: '#/components/schemas/GuitarMaterial'
        neckMaterial:
          type: array
          items:
            $ref: '#/components/schemas/GuitarMaterial'
        numberOfFrets:
          type: integer
          format: int32
        scaleLengthInInches:
          type: number
          format: double
        numberOfStrings:
          type: integer
          format: int32
    GuitarTuning:
      title: GuitarTuning
      type: object
      properties:
        notes:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Note'
    InternalServerError:
      title: InternalServerError
      type: object
      required:
      - message
      properties:
        message:
          type: string
    NotFound:
      title: NotFound
      type: object
      required:
      - message
      properties:
        message:
          type: string
    Note:
      title: Note
      type: object
      required:
      - name
      - octave
      properties:
        name:
          $ref: '#/components/schemas/NoteName'
        octave:
          type: integer
          format: int32
    NoteName:
      title: NoteName
      type: string
      enum:
      - A
      - As
      - B
      - C
      - Cs
      - D
      - Ds
      - E
      - F
      - Fs
      - G
      - Gs
    PartialAlbum:
      title: PartialAlbum
      type: object
      required:
      - id
      - name
      - artist
      - format
      - releaseDate
      properties:
        id:
          type: string
        name:
          type: string
        artist:
          type: string
        format:
          $ref: '#/components/schemas/AlbumFormat'
        releaseDate:
          type: string
          format: date
        genre:
          type: array
          minItems: 1
          items:
            type: string
        review:
          $ref: '#/components/schemas/Review'
    PedalType:
      title: PedalType
      type: string
      enum:
      - Boost
      - Chorus
      - Delay
      - Distortion
      - Fuzz
      - NoiseGate
      - Overdrive
      - PowerAmplifier
      - Preamp
      - Reverb
      - Splitter
      - Tuner
    Pickup:
      title: Pickup
      type: object
      required:
      - type
      - brand
      - model
      properties:
        type:
          $ref: '#/components/schemas/PickupType'
        brand:
          $ref: '#/components/schemas/PickupBrand'
        model:
          type: string
    PickupBrand:
      title: PickupBrand
      type: string
      enum:
      - BareKnuckle
      - DiMarzio
      - Dunable
      - EMG
      - Fishman
      - Lundgren
      - SeymourDuncan
    PickupConfiguration:
      title: PickupConfiguration
      type: object
      required:
      - bridgePickup
      properties:
        neckPickup:
          $ref: '#/components/schemas/Pickup'
        middlePickup:
          $ref: '#/components/schemas/Pickup'
        bridgePickup:
          $ref: '#/components/schemas/Pickup'
    PickupType:
      title: PickupType
      type: string
      enum:
      - Humbucker
      - P90
      - SingleCoil
    Review:
      title: Review
      type: object
      required:
      - title
      - rating
      - description
      properties:
        title:
          type: string
        rating:
          type: integer
          format: int32
          minimum: 0
          maximum: 10
        description:
          type: string
    StringConstruction:
      title: StringConstruction
      type: string
      enum:
      - Plain
      - Wound
    StringRecommendation:
      title: StringRecommendation
      type: object
      required:
      - note
      - spec
      - tensionLbs
      - referenceTensionLbs
      - deltaLbs
      properties:
        note:
          $ref: '#/components/schemas/Note'
        spec:
          $ref: '#/components/schemas/StringSpec'
        tensionLbs:
          type: number
          format: double
        referenceTensionLbs:
          type: number
          format: double
        deltaLbs:
          type: number
          format: double
    StringRecommendationRequest:
      title: StringRecommendationRequest
      type: object
      required:
      - targetTuning
      properties:
        targetTuning:
          $ref: '#/components/schemas/GuitarTuning'
    StringRecommendationResponse:
      title: StringRecommendationResponse
      type: object
      properties:
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/StringRecommendation'
    StringSpec:
      title: StringSpec
      type: object
      required:
      - gauge
      - unitWeight
      - construction
      properties:
        gauge:
          type: number
          format: double
        unitWeight:
          type: number
          format: double
        construction:
          $ref: '#/components/schemas/StringConstruction'
    StringsChanged:
      title: StringsChanged
      type: object
      required:
      - date
      - stringBrand
      - tuning
      properties:
        date:
          type: string
          format: date
        stringBrand:
          type: string
        stringGauge:
          type: array
          items:
            type: number
            format: double
        tuning:
          $ref: '#/components/schemas/GuitarTuning'
    WishlistAlbum:
      title: WishlistAlbum
      type: object
      required:
      - id
      - name
      - artist
      - format
      - releaseDate
      - status
      properties:
        id:
          type: string
        name:
          type: string
        artist:
          type: string
        format:
          $ref: '#/components/schemas/AlbumFormat'
        releaseDate:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/WishlistStatus'
    WishlistStatus:
      title: WishlistStatus
      type: string
      enum:
      - Ordered
      - Received
      - Wanted
