/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/wishlist/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["List Wishlist Albums"];
        put?: never;
        post: operations["Add Album to Wishlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlist/albums/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Confirm Album Received"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlist/albums/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order Album"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["List Albums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guitars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["List Guitars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guitars/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Get Guitar Events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guitars/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Handle Guitar Command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/amplifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["List Amplifiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guitar-pedals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["List Guitar Pedals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddAlbumToWishlist */
        AddAlbumToWishlist: {
            name: string;
            artist: string;
            format: components["schemas"]["AlbumFormat"];
            /** Format: date */
            releaseDate: string;
        };
        /**
         * AlbumFormat
         * @enum {string}
         */
        AlbumFormat: "CD" | "Vinyl";
        /**
         * AmpType
         * @enum {string}
         */
        AmpType: "SolidState" | "Tube";
        /** Amplifier */
        Amplifier: {
            id: string;
            model: string;
            serialNumber: string;
            brand: components["schemas"]["AmplifierBrand"];
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            wattage: number;
            type: components["schemas"]["AmpType"];
        };
        /**
         * AmplifierBrand
         * @enum {string}
         */
        AmplifierBrand: "Revv" | "Victory";
        /** ChangeStrings */
        ChangeStrings: {
            /** Format: date */
            date: string;
            stringBrand: string;
            stringGauge?: number[];
            tuning: components["schemas"]["GuitarTuning"];
        };
        /** Guitar */
        Guitar: {
            id: string;
            model: string;
            brand: components["schemas"]["GuitarBrand"];
            /** Format: int32 */
            year: number;
            serialNumber: string;
            specifications: components["schemas"]["GuitarSpecifications"];
            setup: components["schemas"]["GuitarSetup"];
            events?: components["schemas"]["GuitarEvent"][];
        };
        /**
         * GuitarBrand
         * @enum {string}
         */
        GuitarBrand: "Aristides" | "Charvel" | "Dunable" | "Epiphone" | "Ibanez" | "Jackson" | "Ltd" | "PRS" | "Schecter";
        /** GuitarCommand */
        GuitarCommand: components["schemas"]["ChangeStrings"];
        /** GuitarEvent */
        GuitarEvent: components["schemas"]["StringsChanged"];
        /**
         * GuitarMaterial
         * @enum {string}
         */
        GuitarMaterial: "Alder" | "Arium" | "Ash" | "Basswood" | "Ebony" | "FlamedMaple" | "MacassarEbony" | "Mahogany" | "Mango" | "Maple" | "PauFerro" | "PoplarBurl" | "PurpleHeart" | "QuiltedMaple" | "RichLite" | "RoastedMaple" | "Rosewood" | "SwampAsh" | "Walnut" | "Wenge";
        /** GuitarPedal */
        GuitarPedal: {
            id: string;
            model: string;
            serialNumber: string;
            brand: components["schemas"]["GuitarPedalBrand"];
            /** Format: int32 */
            year: number;
            type: components["schemas"]["PedalType"];
        };
        /**
         * GuitarPedalBrand
         * @enum {string}
         */
        GuitarPedalBrand: "Boss" | "Digitech" | "EarthQuakerDevices" | "Fortin" | "GroundFx" | "Hologram" | "JHS" | "JPTRFX" | "KMAMachines" | "Klirrton" | "LichtlaermAudio" | "OldBloodNoiseEndeavors" | "Revv" | "ScienceAmplification" | "SeymourDuncan" | "StoneDeaf" | "TcElectronic" | "WalrusAudio" | "WayHuge";
        /** GuitarSetup */
        GuitarSetup: {
            stringGauge?: number[];
            stringBrand: string;
            tuning: components["schemas"]["GuitarTuning"];
            /** Format: date */
            lastStringChange: string;
        };
        /** GuitarSpecifications */
        GuitarSpecifications: {
            bodyFinish: string;
            top?: components["schemas"]["GuitarMaterial"];
            bodyMaterial: components["schemas"]["GuitarMaterial"];
            pickupConfiguration: components["schemas"]["PickupConfiguration"];
            fretboardMaterial: components["schemas"]["GuitarMaterial"];
            neckMaterial?: components["schemas"]["GuitarMaterial"][];
            /** Format: int32 */
            numberOfFrets: number;
            /** Format: double */
            scaleLengthInInches: number;
            /** Format: int32 */
            numberOfStrings: number;
        };
        /** GuitarTuning */
        GuitarTuning: {
            notes?: components["schemas"]["Note"][];
        };
        /** Note */
        Note: {
            name: components["schemas"]["NoteName"];
            /** Format: int32 */
            octave: number;
        };
        /**
         * NoteName
         * @enum {string}
         */
        NoteName: "A" | "As" | "B" | "C" | "Cs" | "D" | "Ds" | "E" | "F" | "Fs" | "G" | "Gs";
        /** PartialAlbum */
        PartialAlbum: {
            name: string;
            artist: string;
            format: components["schemas"]["AlbumFormat"];
            /** Format: date */
            releaseDate: string;
        };
        /**
         * PedalType
         * @enum {string}
         */
        PedalType: "Boost" | "Chorus" | "Delay" | "Distortion" | "Fuzz" | "NoiseGate" | "Overdrive" | "PowerAmplifier" | "Preamp" | "Reverb" | "Splitter" | "Tuner";
        /** Pickup */
        Pickup: {
            type: components["schemas"]["PickupType"];
            brand: components["schemas"]["PickupBrand"];
            model: string;
        };
        /**
         * PickupBrand
         * @enum {string}
         */
        PickupBrand: "BareKnuckle" | "DiMarzio" | "Dunable" | "EMG" | "Fishman" | "Lundgren" | "SeymourDuncan";
        /** PickupConfiguration */
        PickupConfiguration: {
            neckPickup?: components["schemas"]["Pickup"];
            middlePickup?: components["schemas"]["Pickup"];
            bridgePickup: components["schemas"]["Pickup"];
        };
        /**
         * PickupType
         * @enum {string}
         */
        PickupType: "Humbucker" | "P90" | "SingleCoil";
        /** StringsChanged */
        StringsChanged: {
            /** Format: date */
            date: string;
            stringBrand: string;
            stringGauge?: number[];
            tuning: components["schemas"]["GuitarTuning"];
        };
        /** WishlistAlbum */
        WishlistAlbum: {
            name: string;
            artist: string;
            format: components["schemas"]["AlbumFormat"];
            /** Format: date */
            releaseDate: string;
            status: components["schemas"]["WishlistStatus"];
        };
        /**
         * WishlistStatus
         * @enum {string}
         */
        WishlistStatus: "Ordered" | "Received" | "Wanted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "List Wishlist Albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistAlbum"][];
                };
            };
        };
    };
    "Add Album to Wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAlbumToWishlist"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid value for: body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "Confirm Album Received": {
        parameters: {
            query: {
                name: string;
                artist: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid value for: query parameter name, Invalid value for: query parameter artist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "Order Album": {
        parameters: {
            query: {
                name: string;
                artist: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid value for: query parameter name, Invalid value for: query parameter artist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "List Albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartialAlbum"][];
                };
            };
        };
    };
    "List Guitars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guitar"][];
                };
            };
        };
    };
    "Get Guitar Events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuitarEvent"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Handle Guitar Command": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuitarCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guitar"];
                };
            };
            /** @description Invalid value for: body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "List Amplifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplifier"][];
                };
            };
        };
    };
    "List Guitar Pedals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuitarPedal"][];
                };
            };
        };
    };
}
